# Generated by Django 5.0.2 on 2025-04-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
