# Generated by Django 5.0.2 on 2025-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_syllabus_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_prompt', models.TextField(default="Please extract only the question text from this image. Do not answer it. Return the question in Arabic if it's in Arabic, otherwise return it as-is.")),
                ('answer_generation_prompt', models.TextField(default='استخرج السؤال من هذه الصورة، ثم أجب عليه باللغة العربية بالاعتماد فقط على محتوى المنهج التالي. إذا لم تجد إجابة دقيقة، استخدم أقرب محتوى متعلق بالإجابة بطريقة منطقية وضمن نطاق المنهج. حاول إعطاء إجابة مقاربة لأكثر محتوى مرتبط بالسؤال.')),
                ('gemini_model_name', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('max_questions_to_keep', models.PositiveIntegerField(default=100, help_text='Maximum number of questions to keep in history (oldest will be deleted)')),
            ],
            options={
                'verbose_name_plural': 'Application Settings',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='prompt',
            field=models.TextField(default='Extract and answer the question from this image based on the syllabus content'),
        ),
    ]
